services:
  serve:
    build: .
    ports:
      - "8000:8000"
    environment:
      PIXELTABLE_HOME: /data/pixeltable
      # OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - pxt-data:/data/pixeltable

volumes:
  pxt-data:
